### ISSUE TITLE
Сломанное условие

### ISSUE THREAD

**Issue by Razdva122** [Alex270387/study#1]
https://github.com/Alex270387/study/blob/a9fc839584624fc743ae865496b9bb721b342403/js/script.js#L30

```9 < 2 < 30 === true``` Такое ли поведение ты ожидаешь?

**Comment by Alex270387** [comment]
когда еще писал, сразу подумал какая то ерунда, но оставил и забыл. Исправил на (9 < personalMovieDB.count && personalMovieDB.count < 30)
